// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/// Auto-generated Firebase configuration for the auth-testing-farhan project.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbyuzQi4fHhfVVL3jReiV44k3Qeul-kQg',
    appId: '1:339288104139:android:cf65f0406679fb51d74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46uBUvmVQKsSL7HIXZG58MD9jXQCFX7c',
    appId: '1:948878883710:ios:5363ad2b9fbe06b2a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV5L960aONby7cvY-cQ7DTe8TSrf2j9rw',
    appId: '1:339288104139:web:dcdfd4ada42ee0eed74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    authDomain: 'auth-testing-farhan.firebaseapp.com',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
    measurementId: 'G-K75JRVP149',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV5L960aONby7cvY-cQ7DTe8TSrf2j9rw',
    appId: '1:339288104139:web:5881793e28ffb6d1d74f4e',
    messagingSenderId: '339288104139',
    projectId: 'auth-testing-farhan',
    authDomain: 'auth-testing-farhan.firebaseapp.com',
    storageBucket: 'auth-testing-farhan.firebasestorage.app',
    measurementId: 'G-2F85WBDYV6',
  );

}